// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BACKSCATTER_MOVEMENT_RECORD_MSGS_SRVS__MSG__ODOM_WITH_EXPMT_FLAG_HPP_
#define BACKSCATTER_MOVEMENT_RECORD_MSGS_SRVS__MSG__ODOM_WITH_EXPMT_FLAG_HPP_

#include "backscatter_movement_record_msgs_srvs/msg/detail/odom_with_expmt_flag__struct.hpp"
#include "backscatter_movement_record_msgs_srvs/msg/detail/odom_with_expmt_flag__builder.hpp"
#include "backscatter_movement_record_msgs_srvs/msg/detail/odom_with_expmt_flag__traits.hpp"
#include "backscatter_movement_record_msgs_srvs/msg/detail/odom_with_expmt_flag__type_support.hpp"

#endif  // BACKSCATTER_MOVEMENT_RECORD_MSGS_SRVS__MSG__ODOM_WITH_EXPMT_FLAG_HPP_
